### ISSUE TITLE
POST throw java.lang.ClassNotFoundException: org.apache.http.HttpEntity

### ISSUE THREAD

**Issue by poliveira89** [Mashape/unirest-java#198]
EDIT: `java version "1.8.0_74"`

I have a private Maven repository and uploaded the artifacts for `Unirest`, `org.json`, `httpclient`, `httpmime`, `httpasyncclient`.

My dependencies on the `pom.xml` is exactly like the example on the homepage:
```xml
    <dependencies>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.3.6</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpasyncclient</artifactId>
            <version>4.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpmime</artifactId>
            <version>4.3.6</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20140107</version>
        </dependency>
        <dependency>
            <groupId>com.mashape.unirest</groupId>
            <artifactId>unirest-java</artifactId>
            <version>1.4.9</version>
        </dependency>
    </dependencies>
```

This is the code I inserted on my `Main.java`
```java
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.JsonNode;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;

public class Main {
    public static void main(String[] args) throws UnirestException {
        HttpResponse<JsonNode> jsonResponse = Unirest.post("http://httpbin.org/post")
                .header("accept", "application/json")
                .queryString("apiKey", "123")
                .field("parameter", "value")
                .field("foo", "bar")
                .asJson();
        System.out.println(jsonResponse.getBody().toString());
    }
}
```

When I run the code this is the output:
```bash
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/HttpEntity
	at com.mashape.unirest.request.HttpRequestWithBody.field(HttpRequestWithBody.java:102)
	at com.mashape.unirest.request.HttpRequestWithBody.field(HttpRequestWithBody.java:94)
	at Main.main(Main.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: org.apache.http.HttpEntity
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
```
With my IDE (Intellij IDEA Community) I have looked into the package `org.apache.http` from `httpclient-4.3.6.jar` jdoes not contain any `HttpEntity` class.

**Comment by poliveira89** [comment]
With a little change to the code:

```java
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.JsonNode;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;

public class Main {
    public static void main(String[] args) throws UnirestException {
        HttpResponse<JsonNode> jsonResponse = Unirest.get("http://httpbin.org/get")
                .header("accept", "application/json")
                .queryString("apiKey", "123")
                .asJson();
        System.out.println(jsonResponse.getBody().toString());
    }
}
```

Retrieve another `ClassNotFoundException` for another class:
```bash
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/HttpRequest
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
	at Main.main(Main.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: org.apache.http.HttpRequest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
```

**Comment by poliveira89** [comment]
I find very strange that the same exact version of the dependencies for the version `1.4.9` of Unirest will return something like `ClassNotFoundException`. And being the first encountering this problem after ~1year of the release of the given version. 😕

**Comment by poliveira89** [comment]
I found that the problem is related to `.asJson()`. I altered my code to:

```java
HttpRequest response = Unirest.get("http://httpbin.org/get")
                .header("accept", "application/json")
                .queryString("apiKey", "123");
        System.out.println(response.getBody());
````

The output was `null` but no errors.

I put into more research into this problem, tried to understand if it was a wider problem and I have encountered this issue #167 suggests the same problem with `.asJson()`.
It was closed several months after by the issuer without any response from the community.

**Comment by MiladAlshomary** [comment]
Hello! I have got the same error?

Any updates on this matter?

**Comment by poliveira89** [comment]
@MiladAlshomary Nope

**Comment by MiladAlshomary** [comment]
@poliveira89 

I have struggled for an hour collecting the dependencies to get this library to run! Here are the list of jars needed to make it run:

unirest-java-1.4.9.jar
httpasyncclient-4.0.2.jar
httpclient-4.3.6.jar
httpmime-4.3.6.jar
json-20140107.jar
httpcore-4.3.jar
org-apache-commons-logging.jar
httpcore-nio-4.3-beta2.jar

**Comment by poliveira89** [comment]
the `httpcore-4.3.jar` and `org-apache-commons-logging.jar` are dependencies from which one dependency?

because in the `pom.xml` I declared the dependencies mentioned on the Unirest homepage/documentation.

**Comment by MiladAlshomary** [comment]
These two jars needed to fulfill the dependencies! Though they are not mentioned in the documentation. It seems that they updated the code but they didn't update the documentation!
