### ISSUE TITLE
org.apache.http.ProtocolException if query parameter too long

### ISSUE THREAD

**Issue by joeyvmason** [Mashape/unirest-java#66]
I'm attempting to make a POST request. However, it's failing with this exception when the length for one of the query strings exceeds ~5285 characters:

```com.mashape.unirest.http.exceptions.UnirestException: org.apache.http.ProtocolException: Not a valid protocol version: <html>```

The value for the parameter is just some basic HTML (`<div>FOO</div>` over and over). If I remove just one of those divs, the request will go through successfully, so I'm pretty sure it just can't process a string of this length. 

This is the request url that is generated:

```
https://api.sendgrid.com/api/newsletter/edit.json?api_user=my_username&api_key=my_key&identity=Default&name=test&subject=test&text=test&html=%0A%3C%21DOCTYPE+html+PUBLIC+%22-%2F%2FW3C%2F%2FDTD+XHTML+1.0+Transitional%2F%2FEN%22+%22https%3A%2F%2Fwww.w3.org%2FTR%2Fxhtml1%2FDTD%2Fxhtml1-transitional.dtd%22%3E%0A%3Chtml+xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxhtml%22+lang%3D%22en%22+xml%3Alang%3D%22en%22%3E%0A++++%3Chead%3E%0A++++++++%3Cmeta+http-equiv%3D%22Content-Type%22+content%3D%22text%2Fhtml%3B+charset%3DUTF-8%22+%2F%3E%0A++++++++%3Ctitle%3EBuy+2+Get+1+Free%3C%2Ftitle%3E%0A++++%3C%2Fhead%3E%0A++++%3Cbody%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++++++%3Cdiv%3EFOO%3C%2Fdiv%3E%0A++++%3C%2Fbody%3E%0A%3C%2Fhtml%3E
```

This is the stack trace:
```
com.mashape.unirest.http.exceptions.UnirestException: org.apache.http.ProtocolException: Not a valid protocol version: <html>
	at com.mashape.unirest.http.HttpClientHelper$1.failed(HttpClientHelper.java:86) [unirest-java-1.3.27.jar:na]
	at org.apache.http.concurrent.BasicFuture.failed(BasicFuture.java:130) [httpcore-4.3.3.jar:4.3.3]
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.failed(DefaultClientExchangeHandlerImpl.java:258) [httpasyncclient-4.0.2.jar:4.0.2]
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.exception(HttpAsyncRequestExecutor.java:123) [httpcore-nio-4.3.2.jar:4.3.2]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:273) [httpcore-nio-4.3.2.jar:4.3.2]
Caused by: org.apache.http.ProtocolException: Not a valid protocol version: <html>
	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:208) ~[httpcore-nio-4.3.2.jar:4.3.2]
	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:245) [httpcore-nio-4.3.2.jar:4.3.2]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:73) [httpasyncclient-4.0.2.jar:4.0.2]
	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:37) [httpasyncclient-4.0.2.jar:4.0.2]
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120) [httpcore-nio-4.3.2.jar:4.3.2]
Caused by: org.apache.http.ParseException: Not a valid protocol version: <html>
	at org.apache.http.message.BasicLineParser.parseProtocolVersion(BasicLineParser.java:132) ~[httpcore-4.3.3.jar:4.3.3]
	at org.apache.http.message.BasicLineParser.parseStatusLine(BasicLineParser.java:361) ~[httpcore-4.3.3.jar:4.3.3]
	at org.apache.http.impl.nio.codecs.DefaultHttpResponseParser.createMessage(DefaultHttpResponseParser.java:114) ~[httpcore-nio-4.3.2.jar:4.3.2]
	at org.apache.http.impl.nio.codecs.DefaultHttpResponseParser.createMessage(DefaultHttpResponseParser.java:51) ~[httpcore-nio-4.3.2.jar:4.3.2]
	at org.apache.http.impl.nio.codecs.AbstractMessageParser.parseHeadLine(AbstractMessageParser.java:156) ~[httpcore-nio-4.3.2.jar:4.3.2]

```

**Comment by thefosk** [comment]
Having large query strings is not recommended, because of limitations by both clients and servers. I've been checking the documentation of the API you're trying to consume at https://sendgrid.com/docs/API_Reference/Marketing_Emails_API/newsletters.html#-edit and it says to put the parameters in the body of the request. 

This means that you need to set each field by invoking `.field(key, value)`

**Comment by joeyvmason** [comment]
Thank you.
