### ISSUE TITLE
Caused by: java.lang.VerifyError: com/mashape/relocation/conn/ssl/AbstractVerifier

### ISSUE THREAD

**Issue by ianjuma** [Mashape/unirest-java#90]
Getting this error - Unirest referencing a missing class?

```
05-08 11:46:56.028  13399-13412/at.jaza.airtime E/dalvikvm﹕ 
Could not find class 'javax.naming.ldap.LdapName', 
referenced from method com.mashape.relocation.conn.ssl.AbstractVerifier.extractCNs
```

Does unirest-java work with android version less than API level 19? 

```bash
Caused by: java.lang.VerifyError: com/mashape/relocation/conn/ssl/AbstractVerifier
            at com.mashape.relocation.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:126)
            at com.mashape.relocation.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:98)
            at com.mashape.relocation.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:105)
            at com.mashape.unirest.http.options.Options.refresh(Options.java:73)
            at com.mashape.unirest.http.options.Options.<clinit>(Options.java:46)
            at com.mashape.unirest.http.HttpClientHelper.prepareRequest(HttpClientHelper.java:154)
            at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:134)
            at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
```

I haven't successfully compiled on higher API levels either.
http://stackoverflow.com/questions/26948888/getting-java-lang-verifyerror-com-mashape-relocation-conn-ssl-abstractverifier

http://stackoverflow.com/questions/100107/reasons-of-getting-a-java-lang-verifyerror

**Comment by Mrcharleyz** [comment]
I have the same problem

**Comment by ianjuma** [comment]
@Mrcharleyz try the android [retrofit-rest-client](http://square.github.io/retrofit/) :dash:
